version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_DATABASE: animes-achimid
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: animes-achimid
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      MONGODB_URI: mongodb://root:password@mongo:27017/animes-achimid?authSource=admin
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - glowroot-data:/app/glowroot-data
    depends_on:
      - mongo

volumes:
  mongo-data:
  glowroot-data:
